# Generated by Django 4.2.2 on 2023-06-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_productimage_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='file',
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='media/image/'),
        ),
    ]
