# Generated by Django 4.2.2 on 2023-10-25 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0007_remove_productimage_file_alter_productimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="brand",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="brands",
                to="product.brand",
                to_field="name",
            ),
        ),
    ]
