version: '2.2'

services:
  postgres:
    image: 'postgres'
    restart: always
    environment:
      POSTGRES_DB: 'ShopStore'
      POSTGRES_USER: 'dasman'
      POSTGRES_PASSWORD: 'mypassword'
    ports:
      - "5432:5432"
    volumes:
        - postgres_data:/var/lib/postgresql/data

  web:
    build: ./
    container_name: musicstore
    restart: always
    command: bash entrypoint.sh
    volumes:
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    ports:
      - 8000:8000
    env_file:
      - .env.dev
    depends_on:
      - postgres

volumes:
  static_volume:
  media_volume:
  postgres_data: